### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by rsoni1** [berkeley-dsc/dlab-finance#12]
Running the NBBO job with 3 nodes (config in nbbo.sbatch) gives the following error. The job runs fine with 4 nodes

15/04/13 16:30:38 WARN TaskSetManager: Lost task 1413.0 in stage 0.0 (TID 1413, n0027.savio0): java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:307)
	at org.apache.spark.storage.DiskBlockObjectWriter$TimeTrackingOutputStream$$anonfun$write$3.apply$mcV$sp(BlockObjectWriter.scala:87)
	at org.apache.spark.storage.DiskBlockObjectWriter.org$apache$spark$storage$DiskBlockObjectWriter$$callWithTiming(BlockObjectWriter.scala:229)
	at org.apache.spark.storage.DiskBlockObjectWriter$TimeTrackingOutputStream.write(BlockObjectWriter.scala:87)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	at org.xerial.snappy.SnappyOutputStream.dumpOutput(SnappyOutputStream.java:300)
	at org.xerial.snappy.SnappyOutputStream.rawWrite(SnappyOutputStream.java:247)
	at org.xerial.snappy.SnappyOutputStream.write(SnappyOutputStream.java:107)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
	at java.io.ObjectOutputStream$BlockDataOutputStream.writeByte(ObjectOutputStream.java:1915)
	at java.io.ObjectOutputStream.writeFatalException(ObjectOutputStream.java:1576)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:351)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:44)
	at org.apache.spark.storage.DiskBlockObjectWriter.write(BlockObjectWriter.scala:204)
	at org.apache.spark.util.collection.ExternalSorter$$anonfun$writePartitionedFile$5$$anonfun$apply$2.apply(ExternalSorter.scala:754)
	at org.apache.spark.util.collection.ExternalSorter$$anonfun$writePartitionedFile$5$$anonfun$apply$2.apply(ExternalSorter.scala:753)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at org.apache.spark.util.collection.ExternalSorter$IteratorForPartition.foreach(ExternalSorter.scala:818)
	at org.apache.spark.util.collection.ExternalSorter$$anonfun$writePartitionedFile$5.apply(ExternalSorter.scala:753)
	at org.apache.spark.util.collection.ExternalSorter$$anonfun$writePartitionedFile$5.apply(ExternalSorter.scala:749)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at org.apache.spark.util.collection.ExternalSorter.writePartitionedFile(ExternalSorter.scala:749)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:68)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:68)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by davclark** [comment]
I'm guessing this may be because you're losing the RAM in the 4th node?

I'm not sure how to profile this. Pinging @jey...

**Comment by jey** [comment]
This is a disk space issue. I suspect that the `SPARK_LOCAL_DIRS` is getting filled up. Do these machines have local disks? If not, I suspect the sysadmins have configured Spark to spill to a ramdisk and that ramdisk is filling up. Not sure though -- the ideal thing would be to run `df -h` on the affected node once the problem has been encountered to figure out which disk is filling up.

**Comment by rsoni1** [comment]
tmp is getting filled up across all three nodes. (see stats below). 

[rsoni@n0074 tmp]$ du -s spark-*;df -h
4	spark-08eeae85-3c84-4ff5-9686-df223f936381
20	spark-217e6413-16ca-4d9a-8c02-5f3003d0ee4c
4	spark-275e7554-a2d4-4c60-846a-23596ebcdf8a
3553084	spark-3027998b-9e23-4ef4-98d4-f134e76b8dc2
4	spark-4daac567-8cd3-4cc3-a83d-1a4745a5f087
4	spark-63256801-f738-4912-9d7b-883d49a5cf6a
4	spark-65cc343d-a44c-422a-8d3c-3f3c380f7eef
20	spark-72f65c75-acc8-40e5-b94e-ec1eef375745
4	spark-dad4f455-08cf-4d22-ba43-188e3d64d18e
4	spark-fde539b6-154c-4fed-bfe3-f3a57f22cac3
4	spark-rsoni-org.apache.spark.deploy.master.Master-1.pid
4	spark-rsoni-org.apache.spark.deploy.worker.Worker-1.pid

15/04/15 12:45:10 INFO TaskSetManager: Starting task 1212.2 in stage 0.0 (TID 1294, n0075.savio0, PROCESS_LOCAL, 1363 bytes)
15/04/15 12:45:10 INFO TaskSetManager: Finished task 765.0 in stage 0.0 (TID 765) in 73955 ms on n0075.savio0 (1204/1578)
Filesystem            Size  Used Avail Use% Mounted on
none                   32G  1.7G   30G   6% /
none                   32G     0   32G   0% /dev/shm
/dev/sda2             3.7G  3.5G   16M 100% /tmp
/dev/sda3             906G   72M  860G   1% /local
10.0.0.52:/vol/BRC_data_vol/chroots
                      1.2T  1.1T  124G  90% /var/chroots
10.0.0.52:/vol/BRC_data_vol/software
                      1.2T  1.1T  124G  90% /global/software
10.0.0.52:/vol/BRC_data_vol/users
                      1.2T  1.1T  124G  90% /global/home/users
10.0.0.52:/vol/BRC_data_vol/groups
                      1.2T  1.1T  124G  90% /global/home/groups
10.0.0.52:/vol/BRC_data_vol/xfer-exec
                      1.2T  1.1T  124G  90% /global/software/xfer-exec
ib-io000.lustre@o2ib:/savio
                      219T  150T   58T  73% /global/scratch

I am confused about this setting. I tried changing the conf by setting local dir to /global/scratch but it's not picking that setting up (see my command below)

spark-submit --master $SPARK_URL --executor-memory 16G --conf "spark.local.dir=/global/home/users/rsoni/tmp" /global/home/users/rsoni/work/dlab-finance/nbbo/nbbo.py

I get the following message in the log

15/04/15 12:42:30 WARN SparkConf: In Spark 1.0 and later spark.local.dir will be overridden by the value set by the cluster manager (via SPARK_LOCAL_DIRS in mesos/standalone and LOCAL_DIRS in YARN).

15/04/15 12:42:32 INFO DiskBlockManager: Created local directory at /global/home/users/rsoni/tmp/spark-9f7d1763-ea80-4865-9ea7-f2a543a69ace/blockmgr-1295c02a-fe42-4a16-bd69-a17848ef15d2

**Comment by rsoni1** [comment]
Modified spark_helper.sh to set SPARK_LOCAL_DIRS to SPARK_WORK_DIR pointing to the lustre file system. This is not a local disk but still fast enough. this is no longer an issue. I'll get some benchmarks in next.

**Comment by jey** [comment]
Awesome!
