### ISSUE TITLE
questions about Pytable

### ISSUE THREAD

**Issue by Jay4869** [berkeley-dsc/dlab-finance#29]
I am trying to learn the Pytable and HDF5, but when I made a small table, It does not work. Could you give me help on it?
```
from tables import *

class Particle(IsDescription):
    identity = StringCol(itemsize=22, dflt=" ", pos=0)  # character String
    idnumber = Int16Col(dflt=1, pos = 1)  # short integer
    speed    = Float32Col(dflt=1, pos = 2)  # single-precision

# Open a file in "w"rite mode
fileh = open_file("objecttree.h5", mode = "w")

# Get the HDF5 root group
root = fileh.root

# Create the groups
group1 = fileh.create_group(root, "group1")
group2 = fileh.create_group(root, "group2")

# Now, create an array in root group
array1 = fileh.create_array(root, "array1", ["string", "array"], "String array")

# Create 2 new tables in group1
table1 = fileh.create_table(group1, "table1", Particle)
table2 = fileh.create_table("/group2", "table2", Particle)

# Create the last table in group2
array2 = fileh.create_array("/group1", "array2", [1,2,3,4])

# Now, fill the tables
for table in (table1, table2):
    # Get the record object associated with the table:
    row = table.row

    # Fill the table with 10 records
    for i in xrange(10):
        # First, assign the values to the Particle record
        row['identity']  = 'This is particle: %2d' % (i)
        row['idnumber'] = i
        row['speed']  = i * 2.

        # This injects the Record values
        row.append()

    # Flush the table buffers
    table.flush()

# Finally, close the file (this also will flush all the remaining buffers!)
fileh.close()
```
I got error is following:
```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    array1 = fileh.create_array(root, "array1", ["string", "array"], "String arr
ay")
  File "c:\Users\jie\Miniconda3\lib\site-packages\tables\file.py", line 1152, in
 create_array
    obj=obj, title=title, byteorder=byteorder)
  File "c:\Users\jie\Miniconda3\lib\site-packages\tables\array.py", line 187, in
 __init__
    byteorder, _log)
  File "c:\Users\jie\Miniconda3\lib\site-packages\tables\leaf.py", line 262, in
__init__
    super(Leaf, self).__init__(parentnode, name, _log)
  File "c:\Users\jie\Miniconda3\lib\site-packages\tables\node.py", line 267, in
__init__
    self._v_objectid = self._g_create()
  File "c:\Users\jie\Miniconda3\lib\site-packages\tables\array.py", line 204, in
 _g_create
    raise TypeError("Array objects cannot currently deal with void, "
TypeError: Array objects cannot currently deal with void, unicode or object arra
ys
```

**Comment by rdhyee** [comment]
See https://github.com/PyTables/PyTables/issues/474, specifically https://github.com/PyTables/PyTables/commit/b7c143054a5d63f1ebda512f470d667de5ebc764

**Comment by davclark** [comment]
I'm not sure I should put this on the PyTables issue tracker, but I'll mention it here... once you get into the scientific computing world, "strings" are generally what python3 calls "bytes". This is actually good breakage in my book - as it illustrates a case where you are naïvely committing bytes to disk without explicitly specifying an encoding.

At some point, someone needs to say something like "the default is going to be utf-8" (which is not what's happening in that doc-fix in PyTables). A more illustrative fix would probably be:

```
array1 = fileh.create_array(
    root, "array1", [s.encode() for s in ["string", "array"]], "String array")
```

The default encoding is utf8. Even safer would be `s.encode('utf8')`.

**Comment by Jay4869** [comment]
Thanks for help. I try it again!

**Comment by Jay4869** [comment]
Fixed under Dav's help!
